version: '3.8'

services:
  backend:
    image: gomu-gomu/ma-java-avancee-projet-backend:0.0.1
    build:
      dockerfile: ./docker/Dockerfile
      context: ./../src/modules/ma-java-avancee-projet-backend
    ports:
      - "8080:8080"
    command: ["scripts/run.sh"]