version: '3.8'

services:
  backend:
    image: gomu-gomu/ma-java-avancee-projet-backend:0.0.1
    build:
      dockerfile: ./docker/Dockerfile
      context: ./../src/modules/ma-java-avancee-projet-backend
    ports:
      - "8080:8080"
    command: ["scripts/run.sh"]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db
      - SPRING_DATASOURCE_USERNAME=usr
      - SPRING_DATASOURCE_PASSWORD=pwd
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: usr@usr.com
      PGADMIN_DEFAULT_PASSWORD: pwd
    ports:
      - "5050:80"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: